### ISSUE TITLE
Wrong check of option "level" and wrong setting of eccLevel

### ISSUE THREAD

**Issue by mcassisa** [dereuromark/cakephp-qrcode#2]
In src/View/Helper/QrCodeHelper.php in function normalizeOptions() $options['level'] is set to ECCLevel::* (which is not a string). Then it is checked against a string, thus defaulting to $options['eccLevel']=ECCLevel::L

**Comment by dereuromark** [comment]
Do you have a proposed fix? Do you want to make a PR here?

**Comment by mcassisa** [comment]
I am not sure I am able to suggest a correct fix. If requested my 2 cents would be to set the key "eccLevel" to the value "L"|"Q"|"M"|"H" instead of having a key "level" set to `EccLevel::L|Q|M|H` that in turn must be converted to "eccLevel". By the way, I also suggest to put there some option keys/values (e.g. addLogoSpace)
The value L|Q|M|H is well documented in chillerlan's php-qrcode, so no trouble for the user

In View/Helper/QrCodeHelper.php

```
`$options += [
                        'version' => Version::AUTO, // to avoid code length issues
                        'scale' => 3,
                        'margin' => 0,
                        'imageBase64' => true,
                        'transparent' => false,
                        'eccLevel' => 'H', // instead of 'level' => EccLevel::L
                        'addLogoSpace' => false
                        'connectPaths' => true,
                        'logoSpaceWidth' => 11,
                        'logoSpaceStartX' =>  13,
                        'logoSpaceStartY' =>  12,
                ];`
```
and remove the now reduntant `switch`:

```                switch ($options['level']) {
                        case 'M':
                                $options['eccLevel'] = EccLevel::M;

                                break;
                        case 'Q':
                                $options['eccLevel'] = EccLevel::Q;

                                break;
                        case 'L':
                                $options['eccLevel'] = EccLevel::L;

                                break;
                        default:
                                $options['eccLevel'] = EccLevel::H;
                }```

**Comment by dereuromark** [comment]
Sure, but wouldnt https://github.com/dereuromark/cakephp-qrcode/commit/cab4405756d4740364269417b8112c5fb24d612d fix it for now?
You can still set your 'level' now as string char, overwriting it if needed.

**Comment by mcassisa** [comment]
It does the job, as far as I can tell
(Yet, I can't get the reason behind renaming the option eccLevel to level)

Il ven 9 ago 2024, 18:50 Mark Scherer ***@***.***> ha scritto:

**Comment by dereuromark** [comment]
Not leaking  implementation details
